/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kucharskipiotr;

import com.kucharskipiotr.adapters.InMemoryBookRepository;
import com.kucharskipiotr.adapters.MockSyncAdapter;
import com.kucharskipiotr.domain.BooksService;
import com.kucharskipiotr.domain.model.Book;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // This could be an API endpoint, or literally anything.
        // It just have to use the BookService.
        // If we did that in Spring, then we would just have the configuration with
        // proper database and outer service injection.

        var memory = new InMemoryBookRepository();
        var adapter = new MockSyncAdapter();
        var service = new BooksService(memory, adapter);

        service.addBook(new Book(1, "hello", null));
        service.addBook(new Book(2, "hello 2", null));

        System.out.println("Books in the system");
        memory.getAllBooks().forEach(book -> {
            System.out.println("Book: " + book.name);
        });

        if (service.reserveBook(1, 1)) {
            System.out.println("Reserved book 1");
        }

        if (!service.reserveBook(1, 1)) {
            System.out.println("Can't reserve the book that was already reserved");
        }

        memory.getAllBooks().forEach(book -> {
            System.out.println("Book: " + book.name + " reserved by " + book.reservedBy);
        });

        service.syncAllBooks();
    }
}
